# Generated by Django 3.2 on 2021-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplyfor',
            name='projectStage',
            field=models.CharField(choices=[(1, '初设'), (2, '施工图'), (3, '技术评判'), (0, '可研'), (4, '后评价')], max_length=20, verbose_name='项目阶段'),
        ),
        migrations.AlterField(
            model_name='projectapplyfor',
            name='projectType',
            field=models.CharField(choices=[(2, '屋顶光伏'), (1, '平地光伏'), (0, '山地光伏')], max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='projectStage',
            field=models.CharField(choices=[(1, '初设'), (2, '施工图'), (3, '技术评判'), (0, '可研'), (4, '后评价')], max_length=20, verbose_name='项目阶段'),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='projectType',
            field=models.CharField(choices=[(2, '屋顶光伏'), (1, '平地光伏'), (0, '山地光伏')], max_length=20, verbose_name='项目类型'),
        ),
    ]
