# Generated by Django 3.2 on 2021-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210630_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectApplyFor',
            fields=[
                ('projectName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='项目名称')),
                ('projectType', models.CharField(max_length=20, verbose_name='项目类型')),
                ('projectStage', models.CharField(max_length=20, verbose_name='项目阶段')),
                ('projectHost', models.CharField(blank=True, max_length=30, verbose_name='项目业主')),
                ('projectHostGroup', models.CharField(blank=True, max_length=50, verbose_name='项目业主集团')),
                ('projectDesign', models.CharField(max_length=50, verbose_name='设计单位')),
                ('projectDate', models.CharField(max_length=20, verbose_name='日期')),
                ('projectStatus', models.CharField(default='待审核', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '项目申请',
                'verbose_name_plural': '项目申请',
            },
        ),
    ]
