# Generated by Django 3.2.4 on 2021-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_projectapplyfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='area',
            field=models.FloatField(blank=True, verbose_name='用地面积'),
        ),
    ]
