# Generated by Django 3.2.4 on 2021-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_siteprofile_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoverview',
            name='projectHost',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='项目业主'),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='projectHostGroup',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目业主集团'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='avgElectricity',
            field=models.FloatField(blank=True, null=True, verbose_name='25年均上网电量'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='avgHours',
            field=models.FloatField(blank=True, null=True, verbose_name='25年均小时数'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='capacityRatio',
            field=models.FloatField(blank=True, null=True, verbose_name='组件与逆变器容配比'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='component',
            field=models.IntegerField(blank=True, null=True, verbose_name='组件'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='firstConnect',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='首次并网'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='firstYearHours',
            field=models.FloatField(blank=True, null=True, verbose_name='首年利用小时数'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='fullConnect',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='全容量并网'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='inclinedRadiation',
            field=models.FloatField(blank=True, null=True, verbose_name='倾斜面辐射量'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='installedAngle',
            field=models.IntegerField(blank=True, null=True, verbose_name='固定安装倾角'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='inverter',
            field=models.IntegerField(blank=True, null=True, verbose_name='逆变器'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='组串方案'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='systemEffience',
            field=models.FloatField(blank=True, null=True, verbose_name='系统效率'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='用地面积'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='avgMonthTemperature',
            field=models.FloatField(blank=True, null=True, verbose_name='最热月平均气温'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='avgSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='多年平均风速'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='breakingGroundDepth',
            field=models.FloatField(blank=True, null=True, verbose_name='多年最大冻土深度'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='maxSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='多年最大风速'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='pollutionLevel',
            field=models.FloatField(blank=True, null=True, verbose_name='污秽等级'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='rainyDays',
            field=models.FloatField(blank=True, null=True, verbose_name='多年平均雷暴日数'),
        ),
    ]
