# Generated by Django 3.2 on 2021-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoverview',
            name='projectDate',
            field=models.CharField(max_length=20, verbose_name='日期'),
        ),
    ]
