# Generated by Django 3.2 on 2021-06-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0002_alter_projectoverview_projectdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoverview',
            name='projectHost',
            field=models.CharField(blank=True, max_length=30, verbose_name='项目业主'),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='projectHostGroup',
            field=models.CharField(blank=True, max_length=50, verbose_name='项目业主集团'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='latitude',
            field=models.CharField(max_length=50, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='longtitude',
            field=models.CharField(max_length=50, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='avgMonthTemperature',
            field=models.FloatField(blank=True, verbose_name='最热月平均气温'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='avgSpeed',
            field=models.FloatField(blank=True, verbose_name='多年平均风速'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='breakingGroundDepth',
            field=models.FloatField(blank=True, verbose_name='多年最大冻土深度'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='maxSpeed',
            field=models.FloatField(blank=True, verbose_name='多年最大风速'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='pollutionLevel',
            field=models.FloatField(blank=True, verbose_name='污秽等级'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='rainyDays',
            field=models.FloatField(blank=True, verbose_name='多年平均雷暴日数'),
        ),
    ]
